[package]
name = "dirtio"
version = "0.1.0"
edition = "2021"

[dependencies]
dirtio-macros = { path = "../dirtio-macros" }

crossbeam-queue = "0.3"
futures = "0.3"
mio = { version = "0.8",  features = ["net", "os-poll"] }
sharded-slab = "0.1"
